# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RatchetCli < Formula
  desc "Interactive AI agent CLI"
  homepage "https://github.com/GoCodeAlone/ratchet-cli"
  version "0.8.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/GoCodeAlone/ratchet-cli/releases/download/v0.8.1/ratchet_darwin_amd64.tar.gz"
      sha256 "2be875bf4dba8f88a6463861909e572d8fe831e417facd32d847973e665c5d35"

      define_method(:install) do
        bin.install "ratchet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/GoCodeAlone/ratchet-cli/releases/download/v0.8.1/ratchet_darwin_arm64.tar.gz"
      sha256 "4de9acdb7259fd92d7a8f2896197c84bdf24f700138c8cb3e45be01753fca290"

      define_method(:install) do
        bin.install "ratchet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/GoCodeAlone/ratchet-cli/releases/download/v0.8.1/ratchet_linux_amd64.tar.gz"
      sha256 "4942e740837243bd8485b56a4ae8589ab0b49943034df02f509ed2e8098e437a"
      define_method(:install) do
        bin.install "ratchet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/GoCodeAlone/ratchet-cli/releases/download/v0.8.1/ratchet_linux_arm64.tar.gz"
      sha256 "193d9947b5c829413d85557cdf4046959fc20aab1f06e0065befc8aaa47600ac"
      define_method(:install) do
        bin.install "ratchet"
      end
    end
  end

  def post_install
    # Ad-hoc codesign so macOS Gatekeeper allows execution
    if OS.mac?
      system "codesign", "--force", "--sign", "-", "#{bin}/ratchet"
    end
  end
end
