# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RatchetCli < Formula
  desc "Interactive AI agent CLI"
  homepage "https://github.com/GoCodeAlone/ratchet-cli"
  version "0.12.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/GoCodeAlone/ratchet-cli/releases/download/v0.12.0/ratchet_darwin_amd64.tar.gz"
      sha256 "c70235a1a9bc4d08e72866faad46151c234b93b64ab5d62131999fca7017f016"

      define_method(:install) do
        bin.install "ratchet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/GoCodeAlone/ratchet-cli/releases/download/v0.12.0/ratchet_darwin_arm64.tar.gz"
      sha256 "4aabcb04feaa1f97a98624401637b75f11dd40d04a2a1c70183187487dbedc3a"

      define_method(:install) do
        bin.install "ratchet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/GoCodeAlone/ratchet-cli/releases/download/v0.12.0/ratchet_linux_amd64.tar.gz"
      sha256 "31e74e1a9775c30eda3f8f04f48deef587f375160d52c3bfdd8b9a990cb6724c"
      define_method(:install) do
        bin.install "ratchet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/GoCodeAlone/ratchet-cli/releases/download/v0.12.0/ratchet_linux_arm64.tar.gz"
      sha256 "4b2b40a9cc71957b9bed486b62c67f724a79da13ccc88b8e78cb51dc0a40a890"
      define_method(:install) do
        bin.install "ratchet"
      end
    end
  end

  def post_install
    # Ad-hoc codesign so macOS Gatekeeper allows execution
    if OS.mac?
      system "codesign", "--force", "--sign", "-", "#{bin}/ratchet"
    end
  end
end
