# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RatchetCli < Formula
  desc "Interactive AI agent CLI"
  homepage "https://github.com/GoCodeAlone/ratchet-cli"
  version "0.2.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/GoCodeAlone/ratchet-cli/releases/download/v0.2.1/ratchet_darwin_amd64.tar.gz"
      sha256 "7785b5c4472175b64f3b336a255ee5f119e8465688543bb50ef232c16cebd60f"

      define_method(:install) do
        bin.install "ratchet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/GoCodeAlone/ratchet-cli/releases/download/v0.2.1/ratchet_darwin_arm64.tar.gz"
      sha256 "0cb3780a7160e48f89571f14e2ecbd35bcf887df30491c384d6dc437fa938f68"

      define_method(:install) do
        bin.install "ratchet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/GoCodeAlone/ratchet-cli/releases/download/v0.2.1/ratchet_linux_amd64.tar.gz"
      sha256 "00c5b809a2d1f552c5b1e0e34ed2367724d2fae0f8a3ee1207c0400846df730f"
      define_method(:install) do
        bin.install "ratchet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/GoCodeAlone/ratchet-cli/releases/download/v0.2.1/ratchet_linux_arm64.tar.gz"
      sha256 "f1b8f21dfe9aae24558cfc233483c843b914d11ea84268f118be8dfe7e98ab39"
      define_method(:install) do
        bin.install "ratchet"
      end
    end
  end

  def post_install
    # Ad-hoc codesign so macOS Gatekeeper allows execution
    if OS.mac?
      system "codesign", "--force", "--sign", "-", "#{bin}/ratchet"
    end
  end
end
