# This file was generated by GoReleaser. DO NOT EDIT.
cask "ratchet" do
  name "ratchet"
  desc "Interactive AI agent CLI"
  homepage "https://github.com/GoCodeAlone/ratchet-cli"
  version "0.1.10"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ratchet"

  on_macos do
    on_intel do
      url "https://github.com/GoCodeAlone/ratchet-cli/releases/download/v#{version}/ratchet_darwin_amd64.tar.gz"
      sha256 "efdcbabfc8afac96a3fa6db97f06aafe1135a6b21a7de3255aaa9133af9ac01d"
    end
    on_arm do
      url "https://github.com/GoCodeAlone/ratchet-cli/releases/download/v#{version}/ratchet_darwin_arm64.tar.gz"
      sha256 "00bd47f5ebcbc9cbd1c5065ca1499e5d037121b215ab6fc8330dad0b218c99f2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/GoCodeAlone/ratchet-cli/releases/download/v#{version}/ratchet_linux_amd64.tar.gz"
      sha256 "8bab3a1da1ca917f1462e0b393d8c3b31a853199b6446c4fc5e1877f908f7547"
    end
    on_arm do
      url "https://github.com/GoCodeAlone/ratchet-cli/releases/download/v#{version}/ratchet_linux_arm64.tar.gz"
      sha256 "233c3846a66ca44e3d124d323ddb2b5e755e0f84dd1d343576d49fd741edcfdd"
    end
  end

  # No zap stanza required
end
