# This file was generated by GoReleaser. DO NOT EDIT.
cask "ratchet-cli" do
  version "0.30.2"

  on_macos do
    on_intel do
      sha256 "a668449cb6f36b3d1ba673811d9b59712f9f61627e58c7a57bf3fb1b57c9001e"
      url "https://github.com/GoCodeAlone/ratchet-cli/releases/download/v#{version}/ratchet_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e0fd889a1e6baf52fbd38e6be5e47af4f1873873a695889abe5efba67c5fa674"
      url "https://github.com/GoCodeAlone/ratchet-cli/releases/download/v#{version}/ratchet_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2fb279a92dc8ee58c7511f886f5d604f2618fe31e90fde0a93507928e288e13a"
      url "https://github.com/GoCodeAlone/ratchet-cli/releases/download/v#{version}/ratchet_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8e049aa6a52c3b458448dbaa84e0b86c4e6c5a86655e4bd9cd2fe58b51406771"
      url "https://github.com/GoCodeAlone/ratchet-cli/releases/download/v#{version}/ratchet_linux_arm64.tar.gz"
    end
  end

  name "ratchet-cli"
  desc "Interactive AI agent CLI"
  homepage "https://github.com/GoCodeAlone/ratchet-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ratchet"

  postflight do
    # Ad-hoc codesign so macOS Gatekeeper allows execution
    if OS.mac?
      system_command "/usr/bin/codesign", args: ["--force", "--sign", "-", "#{staged_path}/ratchet"]
    end
  end

  # No zap stanza required

end
