# This file was generated by GoReleaser. DO NOT EDIT.
cask "ratchet-cli" do
  version "0.30.13"

  on_macos do
    on_intel do
      sha256 "bc04c1b2d04945ee096a181baddddc168551497eaa7ca1915694fa7436f7f78e"
      url "https://github.com/GoCodeAlone/ratchet-cli/releases/download/v#{version}/ratchet_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "dfb68ed335596d15148e0e8bb212d483efd078942152d0921f9255ba26873b7e"
      url "https://github.com/GoCodeAlone/ratchet-cli/releases/download/v#{version}/ratchet_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2a565ec44c5d87a8ac3290d3647fe51acdd95b26b5af721e6b9b25a65a4c959d"
      url "https://github.com/GoCodeAlone/ratchet-cli/releases/download/v#{version}/ratchet_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "12571551a0282c7653e9cccb55b5ccc4dcbe63e75b9d4ab1f416eb4e9dd6672b"
      url "https://github.com/GoCodeAlone/ratchet-cli/releases/download/v#{version}/ratchet_linux_arm64.tar.gz"
    end
  end

  name "ratchet-cli"
  desc "Interactive AI agent CLI"
  homepage "https://github.com/GoCodeAlone/ratchet-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ratchet"

  postflight do
    # Ad-hoc codesign so macOS Gatekeeper allows execution
    if OS.mac?
      system_command "/usr/bin/codesign", args: ["--force", "--sign", "-", "#{staged_path}/ratchet"]
    end
  end

  # No zap stanza required

end
