# This file was generated by GoReleaser. DO NOT EDIT.
cask "ratchet-cli" do
  version "0.30.4"

  on_macos do
    on_intel do
      sha256 "7bb9d8f52c36f751e6a2aa982454f1e3e6bb0cc78770a39dafd94b30e1563897"
      url "https://github.com/GoCodeAlone/ratchet-cli/releases/download/v#{version}/ratchet_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "88be97c3bde98872981eeeb1c1abc39b8a3e833f2c477e48103d7f312e2d1ec9"
      url "https://github.com/GoCodeAlone/ratchet-cli/releases/download/v#{version}/ratchet_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "74b0b3bc55070343d124f04a50cba18b819038b053e6c4fd0b96319e8071b8d4"
      url "https://github.com/GoCodeAlone/ratchet-cli/releases/download/v#{version}/ratchet_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cd838309b59f78c0408c38fda0ada68cb8be1c5966df6f83c2a2d532b4e258b3"
      url "https://github.com/GoCodeAlone/ratchet-cli/releases/download/v#{version}/ratchet_linux_arm64.tar.gz"
    end
  end

  name "ratchet-cli"
  desc "Interactive AI agent CLI"
  homepage "https://github.com/GoCodeAlone/ratchet-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ratchet"

  postflight do
    # Ad-hoc codesign so macOS Gatekeeper allows execution
    if OS.mac?
      system_command "/usr/bin/codesign", args: ["--force", "--sign", "-", "#{staged_path}/ratchet"]
    end
  end

  # No zap stanza required

end
