# This file was generated by GoReleaser. DO NOT EDIT.
cask "ratchet" do
  name "ratchet"
  desc "Interactive AI agent CLI"
  homepage "https://github.com/GoCodeAlone/ratchet-cli"
  version "0.1.12"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ratchet"

  on_macos do
    on_intel do
      url "https://github.com/GoCodeAlone/ratchet-cli/releases/download/v#{version}/ratchet_darwin_amd64.tar.gz"
      sha256 "5e8ddc0cbb6cf64aa793877ecc098ff73d4a70d088a6b051004d83f96251c1c9"
    end
    on_arm do
      url "https://github.com/GoCodeAlone/ratchet-cli/releases/download/v#{version}/ratchet_darwin_arm64.tar.gz"
      sha256 "8eea61bdd1ec6a7579a7535e542298bb403c3b7a0a2a5ac3b8a08faa267840e1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/GoCodeAlone/ratchet-cli/releases/download/v#{version}/ratchet_linux_amd64.tar.gz"
      sha256 "764814eed17ef14bb0d381a23c87645cbf08bc48dab941c625cb91db0574195b"
    end
    on_arm do
      url "https://github.com/GoCodeAlone/ratchet-cli/releases/download/v#{version}/ratchet_linux_arm64.tar.gz"
      sha256 "bf0b02e00c7488fed3bce6ca5d264ed6e3d94647b15ad50589cc8bc5d2a866cf"
    end
  end

  # No zap stanza required
end
