# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeSkills < Formula
  desc "Install Claude Code skill files into workspaces"
  homepage "https://github.com/GoCodeAlone/claude-skills"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/GoCodeAlone/claude-skills/releases/download/v0.1.1/claude-skills_0.1.1_darwin_amd64.tar.gz"
      sha256 "758fe9d9f6bb230ad71fc6adaa4234e1d6108855538345d5980b67cf2c8cd0b8"

      define_method(:install) do
        bin.install "claude-skills"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/GoCodeAlone/claude-skills/releases/download/v0.1.1/claude-skills_0.1.1_darwin_arm64.tar.gz"
      sha256 "b2d7f123cbd80c7eb95b3ce27164d3a27a59bb14ec6c2c480f713d93f1dce867"

      define_method(:install) do
        bin.install "claude-skills"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/GoCodeAlone/claude-skills/releases/download/v0.1.1/claude-skills_0.1.1_linux_amd64.tar.gz"
      sha256 "ede9cb7377569c6745faf5d11935973a29c6b1b6f41eef0d416b9cdaf060536e"
      define_method(:install) do
        bin.install "claude-skills"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/GoCodeAlone/claude-skills/releases/download/v0.1.1/claude-skills_0.1.1_linux_arm64.tar.gz"
      sha256 "ef83fb3c991dd0d289b89004449e8c7a24c3cdde35c50d7133240d49f052bddc"
      define_method(:install) do
        bin.install "claude-skills"
      end
    end
  end
end
